com.fasterxml.jackson.*:* = 2.19.2
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
com.google.guava:guava = 33.5.0-jre
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.baseline:gradle-baseline-java = 6.60.0
com.palantir.gradle.consistentversions:gradle-consistent-versions = 2.31.0
org.assertj:* = 3.27.6
org.junit.jupiter:* = 6.0.0
org.junit.platform:* = 6.0.0
org.apache.commons:commons-lang3 = 3.19.0
org.codehaus.groovy:* = 3.0.25
