apply plugin: 'java-library'
apply plugin: 'java-test-fixtures'
apply plugin: 'com.palantir.external-publish-jar'

dependencies {
    api 'org.junit.jupiter:junit-jupiter-api'
    api 'org.assertj:assertj-core'

    compileOnlyApi 'org.jetbrains:annotations'
    // Just so people can get Gradle autocomplete in text blocks in intellij injected with the
    // Gradle language fragments
    compileOnlyApi gradleApi()

    implementation gradleTestKit()
    implementation 'commons-io:commons-io'
    implementation 'com.google.guava:guava'

    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.platform:junit-platform-testkit'
}
