apply plugin: 'java-library'
apply plugin: 'java-test-fixtures'
apply plugin: 'com.palantir.external-publish-jar'

dependencies {
    api 'org.junit.jupiter:junit-jupiter-api'
    api 'org.assertj:assertj-core'

    api 'org.jetbrains:annotations'
    // Just so people can get Gradle autocomplete in text blocks in intellij injected with the
    // Gradle language fragments
    compileOnlyApi gradleApi()

    implementation gradleTestKit()
    implementation 'commons-io:commons-io'
    implementation 'com.google.guava:guava'

    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.platform:junit-platform-testkit'
}

tasks.named('test', Test) {
    // We need to set the versions of gradle to test aganist as we don't have the gradle plugin installed
    // TODO: Ideally we update this with the gradle plugin somehow - perhaps using the previous published version?
    systemProperty 'com.palantir.gradle.testing.gradle_versions_to_test', '8.12.1,8.14.3'
}
