apply plugin: 'groovy'
apply plugin: 'com.palantir.external-publish-jar'

dependencies {
    api 'com.netflix.nebula:nebula-test'
    implementation 'org.apache.groovy:groovy'
    implementation 'org.spockframework:spock-core'
    compileOnly 'junit:junit'
    runtimeOnly 'org.spockframework:spock-junit4'
    implementation gradleTestKit()
}
